// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'broker_manage_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_BrokerManageModel _$$_BrokerManageModelFromJson(Map<String, dynamic> json) =>
    _$_BrokerManageModel(
      o: json['o'] as int?,
      bn: json['bn'] as String?,
      md: json['md'] as int?,
      mdcmnt: json['mdcmnt'] as String?,
      da: json['da'] as bool?,
      in_: json['in_'] as String?,
      bo: json['bo'] as int?,
      os: json['os'] as String?,
      noe: json['noe'] as int?,
      ad: json['ad'] as String?,
      bs: json['bs'] as String?,
      auc: json['auc'] as bool?,
      ph: json['ph'] as String?,
      fa: json['fa'] as String?,
      em: json['em'] as String?,
      mt: json['mt'] as bool?,
      mtcmnt: json['mtcmnt'] as String?,
      wbt: json['wbt'] as bool?,
      wbtcmnt: json['wbtcmnt'] as String?,
      api: json['api'] as bool?,
      apicmnt: json['apicmnt'] as String?,
      oco: json['oco'] as bool?,
      ococmnt: json['ococmnt'] as String?,
      tof: json['tof'] as bool?,
      tofcmnt: json['tofcmnt'] as String?,
      hedg: json['hedg'] as bool?,
      hedgcmnt: json['hedgcmnt'] as String?,
      tlst: json['tlst'] as bool?,
      tlstcmnt: json['tlstcmnt'] as String?,
      oct: json['oct'] as bool?,
      octcmnt: json['octcmnt'] as String?,
      bon: json['bon'] as bool?,
      boncmnt: json['boncmnt'] as String?,
      cont: json['cont'] as bool?,
      contcmnt: json['contcmnt'] as String?,
      maxl: json['maxl'] as int?,
      maxlcmnt: json['maxlcmnt'] as String?,
      mlot: (json['mlot'] as num?)?.toDouble(),
      mlotcmnt: json['mlotcmnt'] as String?,
      maxlot: (json['maxlot'] as num?)?.toDouble(),
      maxlotcmnt: json['maxlotcmnt'] as String?,
      comi: (json['comi'] as num?)?.toDouble(),
      comicmnt: json['comicmnt'] as String?,
      sfa: json['sfa'] as bool?,
      sfacmnt: json['sfacmnt'] as String?,
      sega: json['sega'] as bool?,
      segacmnt: json['segacmnt'] as String?,
      iom: json['iom'] as bool?,
      iomcmnt: json['iomcmnt'] as String?,
      mnga: json['mnga'] as bool?,
      mngacmnt: json['mngacmnt'] as String?,
      gi: json['gi'] as String?,
      tpt: json['tpt'] as String?,
      mau: json['mau'] as String?,
      afmm: json['afmm'] as String?,
      afmmcmnt: json['afmmcmnt'] as String?,
      deci: json['deci'] as String?,
      scalA: json['scalA'] as String?,
      scalAcmnt: json['scalAcmnt'] as String?,
      lu: json['lu'] as String?,
      sl: json['sl'] as String?,
      tp: json['tp'] as String?,
      pct: json['pct'] as String?,
      rt: json['rt'] as String?,
      bt: json['bt'] as String?,
      ac: json['ac'] as String?,
      at: json['at'] as String?,
      ecnS: json['ecnS'] as String?,
      it: json['it'] as String?,
      fwm: json['fwm'] as String?,
    );

Map<String, dynamic> _$$_BrokerManageModelToJson(
        _$_BrokerManageModel instance) =>
    <String, dynamic>{
      'o': instance.o,
      'bn': instance.bn,
      'md': instance.md,
      'mdcmnt': instance.mdcmnt,
      'da': instance.da,
      'in_': instance.in_,
      'bo': instance.bo,
      'os': instance.os,
      'noe': instance.noe,
      'ad': instance.ad,
      'bs': instance.bs,
      'auc': instance.auc,
      'ph': instance.ph,
      'fa': instance.fa,
      'em': instance.em,
      'mt': instance.mt,
      'mtcmnt': instance.mtcmnt,
      'wbt': instance.wbt,
      'wbtcmnt': instance.wbtcmnt,
      'api': instance.api,
      'apicmnt': instance.apicmnt,
      'oco': instance.oco,
      'ococmnt': instance.ococmnt,
      'tof': instance.tof,
      'tofcmnt': instance.tofcmnt,
      'hedg': instance.hedg,
      'hedgcmnt': instance.hedgcmnt,
      'tlst': instance.tlst,
      'tlstcmnt': instance.tlstcmnt,
      'oct': instance.oct,
      'octcmnt': instance.octcmnt,
      'bon': instance.bon,
      'boncmnt': instance.boncmnt,
      'cont': instance.cont,
      'contcmnt': instance.contcmnt,
      'maxl': instance.maxl,
      'maxlcmnt': instance.maxlcmnt,
      'mlot': instance.mlot,
      'mlotcmnt': instance.mlotcmnt,
      'maxlot': instance.maxlot,
      'maxlotcmnt': instance.maxlotcmnt,
      'comi': instance.comi,
      'comicmnt': instance.comicmnt,
      'sfa': instance.sfa,
      'sfacmnt': instance.sfacmnt,
      'sega': instance.sega,
      'segacmnt': instance.segacmnt,
      'iom': instance.iom,
      'iomcmnt': instance.iomcmnt,
      'mnga': instance.mnga,
      'mngacmnt': instance.mngacmnt,
      'gi': instance.gi,
      'tpt': instance.tpt,
      'mau': instance.mau,
      'afmm': instance.afmm,
      'afmmcmnt': instance.afmmcmnt,
      'deci': instance.deci,
      'scalA': instance.scalA,
      'scalAcmnt': instance.scalAcmnt,
      'lu': instance.lu,
      'sl': instance.sl,
      'tp': instance.tp,
      'pct': instance.pct,
      'rt': instance.rt,
      'bt': instance.bt,
      'ac': instance.ac,
      'at': instance.at,
      'ecnS': instance.ecnS,
      'it': instance.it,
      'fwm': instance.fwm,
    };
