name: new_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  flutter_riverpod: ^2.2.0
  riverpod_generator: ^1.1.1

# use this command for Freezed: flutter pub run build_runner build
# flutter packages pub run build_runner build --delete-conflicting-outputs
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.2.0
  build_runner: ^2.3.3
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - development.env
